apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: sabarivishnu26/medconnect-backend:v1

          ports:
            - containerPort: 4000

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_HOST

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET