name: Deploy MedConnect

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/MedConnect

            git pull origin main

            sudo docker compose down

            sudo docker compose up -d --build